apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: payment-taskrun
  namespace: sock-shop
spec:
  serviceAccountName: tekton-sa
  taskRef:
    name: sock-payment-task
  params:
  - name: IMAGE
    value: "renadbkl/payment"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r
