apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: catalogue-pipline-run
spec:
  pipelineRef:
    name: catalogue-pipline
  serviceAccountName: tekton-sa-catalogue
  resources:
    - name: level-3-project
      resourceRef:
        name: pl-r 
