
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sock-shop-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sock-shop-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services","secrets","deployments", "deployments.apps", "replicasets", "pods"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sock-shop-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-role
subjects:
  - kind: ServiceAccount
    name: sock-shop-sa 
