apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-db-taskrun
  namespace: sock-shop
spec:
  serviceAccountName: tekton-sa
  taskRef:
    name: sock-catalogue-db-task
  params:
  - name: IMAGE
    value: "renadbkl/catalogue-db"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r-catalogue-db
