apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-taskrun
  namespace: test
spec:
  serviceAccountName: tekton-sa-shipping
  taskRef:
    name: sock-shipping-task
  params:
  - name: IMAGE
    value: "renadbkl/shipping"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r-shipping
