apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-master-taskrun
  namespace: test
spec:
  serviceAccountName: tekton-sa-queue-master
  taskRef:
    name: sock-queue-master-task
  params:
  - name: IMAGE
    value: "renadbkl/queue-master"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r-qm
