---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: test
  labels:
    name: front-end
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
        - name: front-end
          image: renadbkl/front-end
          resources:
          ports:
            - containerPort: 8079
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: test
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
  selector:
    name: front-end
