apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pl-r
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/renadbkl/level-3-project
