apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa-front-end
  namespace: test
secrets:
  - name: basic-user-pass-docker
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: front-end-role
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["services","secrets","deployments", "deployments.apps", "replicasets", "pods", "ingresses"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: front-end-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: front-end-role
subjects:
  - kind: ServiceAccount
    name: tekton-sa-front-end
