---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: tekton-test
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: front-end
