apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-front-end-taskrun
spec:
  serviceAccountName: tekton-sa-front-end
  taskRef:
    name: deploy-front-end-task 
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r
