apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: carts-pipline
spec:
  resources:
    - name: level-3-project 
      type: git
  tasks:
    - name: build
      taskRef:
        name: sock-carts-task
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: deploy-carts-task 
      resources:
        inputs: 
        - name: level-3-project
          resource: level-3-project
