apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-taskrun
  namespace: test
spec:
  serviceAccountName: tekton-sa-carts
  taskRef:
    name: sock-carts-task
  params:
  - name: IMAGE
    value: "renadbkl/carts"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r-carts
