apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa-rabbitmq
  namespace: test
secrets:
  - name: basic-user-pass-docker
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services","secrets","deployments", "deployments.apps", "replicasets", "pods"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-role
subjects:
  - kind: ServiceAccount
    name: tekton-sa-rabbitmq
