apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-rabbitmq-task 
spec:
  resources:
    inputs:
    - name: level-3-project
      type: git
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: level-3-project/rabbitmq/rmq-dep.yaml
    - name: namespace
      default: test
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(params.pathToYamlFile)"
        - "-n"
        - "$(params.namespace)"
