apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: deploy-orders-db-taskrun
spec:
  serviceAccountName: tekton-sa-orders-db
  taskRef:
    name: deploy-orders-db-task
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r-orders-db
