apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: orders-pipline-run
spec:
  pipelineRef:
    name: orders-pipline
  serviceAccountName: tekton-sa-orders
  resources:
    - name: level-3-project
      resourceRef:
        name: pl-r 
