apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: e2e-js-test-taskrun
  namespace: test
spec:
  serviceAccountName: tekton-sa-e2e-js-test
  taskRef:
    name: sock-e2e-js-test-task
  params:
  - name: IMAGE
    value: "renadbkl/e2e-js-test"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: pl-r
