apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: carts-pipline-run
spec:
  pipelineRef:
    name: carts-pipline
  serviceAccountName: tekton-sa-carts
  resources:
    - name: level-3-project
      resourceRef:
        name: pl-r 
