apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: user-db-pipline-run
spec:
  pipelineRef:
    name: user-db-pipline
  serviceAccountName: tekton-sa-user-db
  resources:
    - name: level-3-project
      resourceRef:
        name: pl-r 
