apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-end-pipline-run
spec:
  pipelineRef:
    name: front-end-pipline
  serviceAccountName: tekton-sa-front-end
  resources:
    - name: level-3-project
      resourceRef:
        name: pl-r 
