---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      k : front-end
  template:
    metadata:
      labels:
        k : front-end
    spec:
      containers:
        - name: front-end
          image: renadbl/front-end
          resources:
          ports:
            - containerPort: 8079
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: catalogue

